runtime: python
env: flex
entrypoint: gunicorn -k eventlet -w 1 HorsieServer.Setup:app
runtime_config:
      python_version: 3

network:
  session_affinity: true

instance_class: F1
automatic_scaling:
  max_num_instances: 1